# Generated by Django 5.2.1 on 2025-05-12 13:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markup_percentage', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5)),
                ('min_withdrawal_amount', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=10)),
                ('support_email', models.EmailField(default='support@yoursite.com', max_length=254)),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
        ),
    ]
