# Generated by Django 5.2.1 on 2025-05-14 13:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_providerpayment_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(default='contact@yoursite.com', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='min_deposit',
            field=models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_description',
            field=models.TextField(blank=True, default='Social Media Marketing Platform'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='SocialBoost', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='support_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
